version: '3.9'

services:
  kong:
    image: kong-custom-plugin:latest
    user: kong
    environment:
      KONG_DECLARATIVE_CONFIG: "/kong.yaml"
      KONG_DATABASE: "off"
      KONG_PROXY_LISTEN: "0.0.0.0:8080"
      KONG_ADMIN_LISTEN: "0.0.0.0:8081"
      KONG_PLUGINS: bundled,kong-plugin-hello
    ports:
      - "0.0.0.0:8080:8080/tcp"
      - "0.0.0.0:8081:8081/tcp"
      - "0.0.0.0:8443:8443/tcp"
      - "0.0.0.0:8444:8444/tcp"
    volumes:
      - ./kong.yaml:/kong.yaml:ro