version: '3.9'

networks:
  kong-net:
    driver: bridge

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8088:8001
    networks:
      - kong-net
  wiremock:
    image: wiremock/wiremock:latest
    command: --port 8880
    ports:
      - 8880:8880
    volumes:
      - ./config/wiremock:/home/wiremock:ro
    networks:
      - kong-net
  kong:
    image: kong-custom-plugin:latest
    depends_on:
      - redis
      - wiremock
    user: kong
    environment:
      KONG_DECLARATIVE_CONFIG: "/config/kong/kong.yaml"
      KONG_DATABASE: "off"
      KONG_PROXY_LISTEN: "0.0.0.0:8080"
      KONG_ADMIN_LISTEN: "0.0.0.0:8081"
      KONG_PLUGINS: bundled,kong-plugin-encryption
    ports:
      - "0.0.0.0:8080:8080/tcp"
      - "0.0.0.0:8081:8081/tcp"
      - "0.0.0.0:8443:8443/tcp"
      - "0.0.0.0:8444:8444/tcp"
    volumes:
      - ./config/kong/kong.yaml:/config/kong/kong.yaml:ro
    networks:
      - kong-net
